name: Feature Request
description: File a feature request.
title: '[Feature Request]: '
labels: ['enhancement', 'triage']
body:
  - type: checkboxes
    id: known-request
    attributes:
      label: Is this a known issue?
      description: Please search through our [Known Issues](../../docs/KNOWN_ISSUES.md) to see if this feature has been requested.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the feature request
      description: Please include relevant mockup images
      value: 'I would like to see...'
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../../CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
